name: iris
description: "A lightweight video player"
publish_to: 'none'
version: 1.5.0+3

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: any
  file_picker: ^10.3.3
  flutter_breadcrumb: ^1.0.1
  flutter_hooks: ^0.21.3+1
  flutter_secure_storage: ^8.1.0
  flutter_zustand: ^0.0.5
  media_kit: ^1.2.0
  media_kit_video: ^1.3.0
  media_kit_libs_video: ^1.0.6
  path: ^1.9.1
  path_provider: ^2.1.5
  package_info_plus: ^9.0.0
  provider: ^6.1.5
  webdav_client: ^1.2.2
  window_manager: ^0.5.1
  url_launcher: ^6.3.2
  scrollable_positioned_list: ^0.3.8
  google_fonts: ^6.3.1
  dynamic_color: ^1.8.1
  window_size: ^0.1.0
  uuid: ^4.5.1
  flutter_markdown: ^0.7.7+1
  http: ^1.5.0
  collection: ^1.19.1
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  disks_desktop: ^1.0.1
  android_x_storage: ^1.0.2
  permission_handler: ^12.0.1
  desktop_drop: ^0.6.1
  app_links: ^6.4.1
  device_info_plus: ^12.0.0
  saf_util: ^0.11.0
  screen_brightness: ^2.1.7
  flutter_volume_controller: ^1.3.3
  fvp: ^0.34.0
  video_player: ^2.10.0
  wakelock_plus: ^1.4.0
  popover: ^0.3.1
  pure_ftp: ^0.7.5
  drives_windows:
    git:
      url: https://github.com/nini22P/drives_windows
      ref: main
  media_stream:
    git:
      url: https://github.com/nini22P/media_stream
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_oss_licenses: ^3.0.6
  build_runner: ^2.8.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  msix: ^3.16.12

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

msix_config:
  display_name: IRIS player
  identity_name: 22P.IRISplayer
  publisher_display_name: 22P
  publisher: CN=9740B6B2-E777-4F52-8ECD-C4A577A73010
  msix_version: 1.5.0.0
  logo_path: assets/images/logo.png
  trim_logo: false
  languages: en-us, zh-cn
  execution_alias: iris
  file_extension: .3gp, .avi, .dpx, .dv, .f4v, .flv, .he264, .hevc, .h265, .mkv, .mp4, .mpeg, .mpg, .mov, .nsv, .rm, .rmvb, .ts, .vob, .webm, .wmv, .aac, .aiff, .alac, .cda, .dsd, .flac, .m4a, .midi, .mp3, .ogg, .opus, .raw, .wav, .wma